# Generated by Django 4.0.1 on 2022-02-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_words', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NinjaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_word', models.CharField(max_length=50)),
                ('is_tech_word', models.BooleanField(default=False)),
                ('is_in_dictionary', models.BooleanField(default=False)),
                ('ninja_word_type', models.CharField(blank=True, max_length=1, null=True)),
                ('ninja_word', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ninja_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninja_namer.ninjaname')),
            ],
        ),
    ]
