# Generated by Django 4.0.1 on 2022-02-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_namer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('first_letter', models.CharField(max_length=1)),
                ('word_type', models.CharField(choices=[('N', 'Noun'), ('A', 'Adjective')], max_length=1)),
                ('adjective_type', models.IntegerField(blank=True, choices=[(1, 'Opinion'), (2, 'Size'), (3, 'Shape'), (4, 'Age'), (5, 'Color'), (6, 'Origin'), (7, 'Material'), (8, 'Purpose')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ninjaword',
            name='ninja_word_type',
            field=models.CharField(blank=True, choices=[('N', 'Noun'), ('A', 'Adjective')], max_length=1, null=True),
        ),
    ]
