# Generated by Django 4.0.1 on 2022-02-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_namer', '0003_rename_ninjawords_ninjawordoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjaword',
            name='ninja_word_type',
        ),
        migrations.AlterField(
            model_name='ninjaword',
            name='ninja_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninja_namer.ninjawordoptions'),
        ),
    ]
