# Generated by Django 4.0.1 on 2022-02-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_namer', '0002_ninjawords_alter_ninjaword_ninja_word_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NinjaWords',
            new_name='NinjaWordOptions',
        ),
    ]
